
export const Actions = {
	FETCH_DATA: 'FETCH_DATA',
	FETCH_DATA_SUCCESS: 'FETCH_DATA_SUCCESS',
	TABLE_SORT: 'TABLE_SORT',
	TABLE_SORT_SUCCESS: 'TABLE_SORT_SUCCESS',
	TABLE_SORT_FAILURE: 'TABLE_SORT_FAILURE',
	TABLE_SEARCH: 'TABLE_SEARCH',
	TABLE_ALL_SEARCH: 'TABLE_ALL_SEARCH',
	TABLE_SELECT_ROLE: 'TABLE_SELECT_ROLE',
	FETCH_ALL_DATA_SUCCESS: 'FETCH_ALL_DATA_SUCCESS',
	TABLE_DELET_STUDENT: 'TABLE_DELET_STUDENT',
	TABLE_DELET_SELECTED_STUDENT: 'TABLE_DELET_SELECTED_STUDENT',
	START_TABLE_SELECT_ROLE: 'START_TABLE_SELECT_ROLE',
}
